spring.application.name=config-server
server.port=8888

# ===== GIT BACKEND =====
# Points to your dedicated config repo on GitHub
spring.cloud.config.server.git.uri=https://github.com/aasghar09/spring-boot-microservices-config
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.force-pull=true

# ===== EUREKA =====
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# ===== ACTUATOR =====
management.endpoints.web.exposure.include=health,info